"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
show_hidden = true
sort_by = "btime"
sort_reverse = true

[opener]
edit = [
  { run = "zed %*", for = "macos" },
  { run = "nvim %*", for = "linux" }
]
